
#
# **************************************************************
# *                  SIMUSOL PROYECT                           *
# *                                                            *
# *                    SimPlot                                 *
# *                                                            *
# *                                                            *
# *   Developed by                                             *
# *        *
# *   and could be used with GPL                               *
# *   or every free license with copyleft needed.              *
# *                                     *
# **************************************************************

#
#    SimPlot is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    SimPlot is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Table.  If not, see <http://www.gnu.org/licenses/>.

#VERSION=2017.0.1
#NAME=simusol_Plot


all: 

	apt-get install libtk-perl;
	apt-get install libtkx-perl;
	cpan Data::Dumper Tk::Tree JSON List::MoreUtils;
	cpan Tie::IxHash;
	cpan Tie::IxHash::Easy;
	cpan Storable;


